<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ2IKUCa\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ2IKUCa/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZ2IKUCa.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZ2IKUCa\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZ2IKUCa\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Z2IKUCa',
    'container.build_id' => 'c4bf9a7c',
    'container.build_time' => 1539173348,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ2IKUCa');
