<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWvqrOaF\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWvqrOaF/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWvqrOaF.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWvqrOaF\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWvqrOaF\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WvqrOaF',
    'container.build_id' => '33f83fb5',
    'container.build_time' => 1539169238,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWvqrOaF');
