<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQCdfWXV\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQCdfWXV/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQCdfWXV.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQCdfWXV\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQCdfWXV\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QCdfWXV',
    'container.build_id' => '73a2f9f5',
    'container.build_time' => 1539172464,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQCdfWXV');
